name: Nix CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  - pull_request

jobs:
  check:
    runs-on: nix-flakes

    steps:
      - name: Set up attic binary cache
        uses: https://git.naxdy.org/Mirror/attic-action@v0.3
        with:
          endpoint: '${{ vars.BINARY_CACHE_URL }}'
          token: '${{ secrets.BINARY_CACHE_AUTH_KEY }}'
          cache: '${{ vars.BINARY_CACHE_NAME }}'

      - uses: actions/checkout@v4

      - name: Fetch flake inputs
        run: |
          nix flake prefetch-inputs

      - name: Run flake checks
        run: |
          nix flake check -j auto --print-build-logs --keep-going
